theatres_schema ="""CREATE TABLE theatres(
	name TEXT,
	path_name TEXT,
	theatre_code TEXT,
	message_start TEXT,
	message_end TEXT,
	message_title TEXT,
	theatre_info_message TEXT,
	address TEXT,
	city TEXT,
	state TEXT,
	postal_code TEXT,
	latitude REAL,
	longitude REAL,
	phone_number TEXT,
	pwp_availability INTEGER,
	iana_timezone TEXT,
    """